apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: service-api
  name: service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: service-api
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: 192.168.1.83
            - name: DB_NAME
              value: solar_controller_telemetry
            - name: DB_PASSWORD
              value: gen_postgress_password
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: EXP_LIMIT
              value: "600"
            - name: REDIS_HOST
              value: 192.168.1.83
            - name: REDIS_PORT
              value: "6379"
            - name: SECRET_KEY
              value: uw3cok92adxmzpf35_secret_key_value_12082025
            - name: SSE_UPDATE_COMPLEX_STATUS_TIMEOUT
              value: "3"
            - name: SSE_UPDATE_DYNAMIC_DATA_TIMEOUT
              value: "10"
            - name: SSE_UPDATE_GPIO_TIMEOUT
              value: "5"
          image: localhost:5000/complex_api:latest
          name: complex-api-service
          ports:
            - containerPort: 5011
              protocol: TCP
      restartPolicy: Always
