from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DynamicDataGet200ResponseMessageLoad(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amps=None, state=None, volts=None, watts=None, max_amps=None, daily_power=None, total_power=None, daily_amp_hours=None, total_amp_hours=None):  # noqa: E501
        """DynamicDataGet200ResponseMessageLoad - a model defined in OpenAPI

        :param amps: The amps of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type amps: float
        :param state: The state of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type state: bool
        :param volts: The volts of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type volts: float
        :param watts: The watts of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type watts: float
        :param max_amps: The max_amps of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type max_amps: float
        :param daily_power: The daily_power of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type daily_power: float
        :param total_power: The total_power of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type total_power: float
        :param daily_amp_hours: The daily_amp_hours of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type daily_amp_hours: float
        :param total_amp_hours: The total_amp_hours of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :type total_amp_hours: float
        """
        self.openapi_types = {
            'amps': float,
            'state': bool,
            'volts': float,
            'watts': float,
            'max_amps': float,
            'daily_power': float,
            'total_power': float,
            'daily_amp_hours': float,
            'total_amp_hours': float
        }

        self.attribute_map = {
            'amps': 'amps',
            'state': 'state',
            'volts': 'volts',
            'watts': 'watts',
            'max_amps': 'maxAmps',
            'daily_power': 'dailyPower',
            'total_power': 'totalPower',
            'daily_amp_hours': 'dailyAmpHours',
            'total_amp_hours': 'totalAmpHours'
        }

        self._amps = amps
        self._state = state
        self._volts = volts
        self._watts = watts
        self._max_amps = max_amps
        self._daily_power = daily_power
        self._total_power = total_power
        self._daily_amp_hours = daily_amp_hours
        self._total_amp_hours = total_amp_hours

    @classmethod
    def from_dict(cls, dikt) -> 'DynamicDataGet200ResponseMessageLoad':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _dynamic_data_get_200_response_message_load of this DynamicDataGet200ResponseMessageLoad.  # noqa: E501
        :rtype: DynamicDataGet200ResponseMessageLoad
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amps(self) -> float:
        """Gets the amps of this DynamicDataGet200ResponseMessageLoad.


        :return: The amps of this DynamicDataGet200ResponseMessageLoad.
        :rtype: float
        """
        return self._amps

    @amps.setter
    def amps(self, amps: float):
        """Sets the amps of this DynamicDataGet200ResponseMessageLoad.


        :param amps: The amps of this DynamicDataGet200ResponseMessageLoad.
        :type amps: float
        """

        self._amps = amps

    @property
    def state(self) -> bool:
        """Gets the state of this DynamicDataGet200ResponseMessageLoad.


        :return: The state of this DynamicDataGet200ResponseMessageLoad.
        :rtype: bool
        """
        return self._state

    @state.setter
    def state(self, state: bool):
        """Sets the state of this DynamicDataGet200ResponseMessageLoad.


        :param state: The state of this DynamicDataGet200ResponseMessageLoad.
        :type state: bool
        """

        self._state = state

    @property
    def volts(self) -> float:
        """Gets the volts of this DynamicDataGet200ResponseMessageLoad.


        :return: The volts of this DynamicDataGet200ResponseMessageLoad.
        :rtype: float
        """
        return self._volts

    @volts.setter
    def volts(self, volts: float):
        """Sets the volts of this DynamicDataGet200ResponseMessageLoad.


        :param volts: The volts of this DynamicDataGet200ResponseMessageLoad.
        :type volts: float
        """

        self._volts = volts

    @property
    def watts(self) -> float:
        """Gets the watts of this DynamicDataGet200ResponseMessageLoad.


        :return: The watts of this DynamicDataGet200ResponseMessageLoad.
        :rtype: float
        """
        return self._watts

    @watts.setter
    def watts(self, watts: float):
        """Sets the watts of this DynamicDataGet200ResponseMessageLoad.


        :param watts: The watts of this DynamicDataGet200ResponseMessageLoad.
        :type watts: float
        """

        self._watts = watts

    @property
    def max_amps(self) -> float:
        """Gets the max_amps of this DynamicDataGet200ResponseMessageLoad.


        :return: The max_amps of this DynamicDataGet200ResponseMessageLoad.
        :rtype: float
        """
        return self._max_amps

    @max_amps.setter
    def max_amps(self, max_amps: float):
        """Sets the max_amps of this DynamicDataGet200ResponseMessageLoad.


        :param max_amps: The max_amps of this DynamicDataGet200ResponseMessageLoad.
        :type max_amps: float
        """

        self._max_amps = max_amps

    @property
    def daily_power(self) -> float:
        """Gets the daily_power of this DynamicDataGet200ResponseMessageLoad.


        :return: The daily_power of this DynamicDataGet200ResponseMessageLoad.
        :rtype: float
        """
        return self._daily_power

    @daily_power.setter
    def daily_power(self, daily_power: float):
        """Sets the daily_power of this DynamicDataGet200ResponseMessageLoad.


        :param daily_power: The daily_power of this DynamicDataGet200ResponseMessageLoad.
        :type daily_power: float
        """

        self._daily_power = daily_power

    @property
    def total_power(self) -> float:
        """Gets the total_power of this DynamicDataGet200ResponseMessageLoad.


        :return: The total_power of this DynamicDataGet200ResponseMessageLoad.
        :rtype: float
        """
        return self._total_power

    @total_power.setter
    def total_power(self, total_power: float):
        """Sets the total_power of this DynamicDataGet200ResponseMessageLoad.


        :param total_power: The total_power of this DynamicDataGet200ResponseMessageLoad.
        :type total_power: float
        """

        self._total_power = total_power

    @property
    def daily_amp_hours(self) -> float:
        """Gets the daily_amp_hours of this DynamicDataGet200ResponseMessageLoad.


        :return: The daily_amp_hours of this DynamicDataGet200ResponseMessageLoad.
        :rtype: float
        """
        return self._daily_amp_hours

    @daily_amp_hours.setter
    def daily_amp_hours(self, daily_amp_hours: float):
        """Sets the daily_amp_hours of this DynamicDataGet200ResponseMessageLoad.


        :param daily_amp_hours: The daily_amp_hours of this DynamicDataGet200ResponseMessageLoad.
        :type daily_amp_hours: float
        """

        self._daily_amp_hours = daily_amp_hours

    @property
    def total_amp_hours(self) -> float:
        """Gets the total_amp_hours of this DynamicDataGet200ResponseMessageLoad.


        :return: The total_amp_hours of this DynamicDataGet200ResponseMessageLoad.
        :rtype: float
        """
        return self._total_amp_hours

    @total_amp_hours.setter
    def total_amp_hours(self, total_amp_hours: float):
        """Sets the total_amp_hours of this DynamicDataGet200ResponseMessageLoad.


        :param total_amp_hours: The total_amp_hours of this DynamicDataGet200ResponseMessageLoad.
        :type total_amp_hours: float
        """

        self._total_amp_hours = total_amp_hours
