from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.system_info_get200_response_message import SystemInfoGet200ResponseMessage
from openapi_server import util

from openapi_server.models.system_info_get200_response_message import SystemInfoGet200ResponseMessage  # noqa: E501

class SystemInfoGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """SystemInfoGet200Response - a model defined in OpenAPI

        :param message: The message of this SystemInfoGet200Response.  # noqa: E501
        :type message: SystemInfoGet200ResponseMessage
        """
        self.openapi_types = {
            'message': SystemInfoGet200ResponseMessage
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'SystemInfoGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _system_info_get_200_response of this SystemInfoGet200Response.  # noqa: E501
        :rtype: SystemInfoGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> SystemInfoGet200ResponseMessage:
        """Gets the message of this SystemInfoGet200Response.


        :return: The message of this SystemInfoGet200Response.
        :rtype: SystemInfoGet200ResponseMessage
        """
        return self._message

    @message.setter
    def message(self, message: SystemInfoGet200ResponseMessage):
        """Sets the message of this SystemInfoGet200Response.


        :param message: The message of this SystemInfoGet200Response.
        :type message: SystemInfoGet200ResponseMessage
        """

        self._message = message
