from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ClearHistoryPost200ResponseMessage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, error_text=None):  # noqa: E501
        """ClearHistoryPost200ResponseMessage - a model defined in OpenAPI

        :param success: The success of this ClearHistoryPost200ResponseMessage.  # noqa: E501
        :type success: bool
        :param error_text: The error_text of this ClearHistoryPost200ResponseMessage.  # noqa: E501
        :type error_text: str
        """
        self.openapi_types = {
            'success': bool,
            'error_text': str
        }

        self.attribute_map = {
            'success': 'success',
            'error_text': 'errorText'
        }

        self._success = success
        self._error_text = error_text

    @classmethod
    def from_dict(cls, dikt) -> 'ClearHistoryPost200ResponseMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _clear_history_post_200_response_message of this ClearHistoryPost200ResponseMessage.  # noqa: E501
        :rtype: ClearHistoryPost200ResponseMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this ClearHistoryPost200ResponseMessage.


        :return: The success of this ClearHistoryPost200ResponseMessage.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this ClearHistoryPost200ResponseMessage.


        :param success: The success of this ClearHistoryPost200ResponseMessage.
        :type success: bool
        """

        self._success = success

    @property
    def error_text(self) -> str:
        """Gets the error_text of this ClearHistoryPost200ResponseMessage.


        :return: The error_text of this ClearHistoryPost200ResponseMessage.
        :rtype: str
        """
        return self._error_text

    @error_text.setter
    def error_text(self, error_text: str):
        """Sets the error_text of this ClearHistoryPost200ResponseMessage.


        :param error_text: The error_text of this ClearHistoryPost200ResponseMessage.
        :type error_text: str
        """

        self._error_text = error_text
