from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DynamicDataGet200ResponseMessagePanels(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amps=None, volts=None):  # noqa: E501
        """DynamicDataGet200ResponseMessagePanels - a model defined in OpenAPI

        :param amps: The amps of this DynamicDataGet200ResponseMessagePanels.  # noqa: E501
        :type amps: float
        :param volts: The volts of this DynamicDataGet200ResponseMessagePanels.  # noqa: E501
        :type volts: float
        """
        self.openapi_types = {
            'amps': float,
            'volts': float
        }

        self.attribute_map = {
            'amps': 'amps',
            'volts': 'volts'
        }

        self._amps = amps
        self._volts = volts

    @classmethod
    def from_dict(cls, dikt) -> 'DynamicDataGet200ResponseMessagePanels':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _dynamic_data_get_200_response_message_panels of this DynamicDataGet200ResponseMessagePanels.  # noqa: E501
        :rtype: DynamicDataGet200ResponseMessagePanels
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amps(self) -> float:
        """Gets the amps of this DynamicDataGet200ResponseMessagePanels.


        :return: The amps of this DynamicDataGet200ResponseMessagePanels.
        :rtype: float
        """
        return self._amps

    @amps.setter
    def amps(self, amps: float):
        """Sets the amps of this DynamicDataGet200ResponseMessagePanels.


        :param amps: The amps of this DynamicDataGet200ResponseMessagePanels.
        :type amps: float
        """

        self._amps = amps

    @property
    def volts(self) -> float:
        """Gets the volts of this DynamicDataGet200ResponseMessagePanels.


        :return: The volts of this DynamicDataGet200ResponseMessagePanels.
        :rtype: float
        """
        return self._volts

    @volts.setter
    def volts(self, volts: float):
        """Sets the volts of this DynamicDataGet200ResponseMessagePanels.


        :param volts: The volts of this DynamicDataGet200ResponseMessagePanels.
        :type volts: float
        """

        self._volts = volts
