from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.clear_history_post200_response_message import ClearHistoryPost200ResponseMessage
from openapi_server import util

from openapi_server.models.clear_history_post200_response_message import ClearHistoryPost200ResponseMessage  # noqa: E501

class ClearHistoryPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """ClearHistoryPost200Response - a model defined in OpenAPI

        :param message: The message of this ClearHistoryPost200Response.  # noqa: E501
        :type message: ClearHistoryPost200ResponseMessage
        """
        self.openapi_types = {
            'message': ClearHistoryPost200ResponseMessage
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ClearHistoryPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _clear_history_post_200_response of this ClearHistoryPost200Response.  # noqa: E501
        :rtype: ClearHistoryPost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> ClearHistoryPost200ResponseMessage:
        """Gets the message of this ClearHistoryPost200Response.


        :return: The message of this ClearHistoryPost200Response.
        :rtype: ClearHistoryPost200ResponseMessage
        """
        return self._message

    @message.setter
    def message(self, message: ClearHistoryPost200ResponseMessage):
        """Sets the message of this ClearHistoryPost200Response.


        :param message: The message of this ClearHistoryPost200Response.
        :type message: ClearHistoryPost200ResponseMessage
        """

        self._message = message
