from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.dynamic_data_get200_response_message import DynamicDataGet200ResponseMessage
from openapi_server import util

from openapi_server.models.dynamic_data_get200_response_message import DynamicDataGet200ResponseMessage  # noqa: E501

class DynamicDataGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """DynamicDataGet200Response - a model defined in OpenAPI

        :param message: The message of this DynamicDataGet200Response.  # noqa: E501
        :type message: DynamicDataGet200ResponseMessage
        """
        self.openapi_types = {
            'message': DynamicDataGet200ResponseMessage
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'DynamicDataGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _dynamic_data_get_200_response of this DynamicDataGet200Response.  # noqa: E501
        :rtype: DynamicDataGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> DynamicDataGet200ResponseMessage:
        """Gets the message of this DynamicDataGet200Response.


        :return: The message of this DynamicDataGet200Response.
        :rtype: DynamicDataGet200ResponseMessage
        """
        return self._message

    @message.setter
    def message(self, message: DynamicDataGet200ResponseMessage):
        """Sets the message of this DynamicDataGet200Response.


        :param message: The message of this DynamicDataGet200Response.
        :type message: DynamicDataGet200ResponseMessage
        """

        self._message = message
