from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.dynamic_data_get200_response_message_battery import DynamicDataGet200ResponseMessageBattery
from openapi_server.models.dynamic_data_get200_response_message_charging import DynamicDataGet200ResponseMessageCharging
from openapi_server.models.dynamic_data_get200_response_message_controller import DynamicDataGet200ResponseMessageController
from openapi_server.models.dynamic_data_get200_response_message_load import DynamicDataGet200ResponseMessageLoad
from openapi_server.models.dynamic_data_get200_response_message_panels import DynamicDataGet200ResponseMessagePanels
from openapi_server import util

from openapi_server.models.dynamic_data_get200_response_message_battery import DynamicDataGet200ResponseMessageBattery  # noqa: E501
from openapi_server.models.dynamic_data_get200_response_message_charging import DynamicDataGet200ResponseMessageCharging  # noqa: E501
from openapi_server.models.dynamic_data_get200_response_message_controller import DynamicDataGet200ResponseMessageController  # noqa: E501
from openapi_server.models.dynamic_data_get200_response_message_load import DynamicDataGet200ResponseMessageLoad  # noqa: E501
from openapi_server.models.dynamic_data_get200_response_message_panels import DynamicDataGet200ResponseMessagePanels  # noqa: E501

class DynamicDataGet200ResponseMessage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, load=None, faults=None, modbus_error=None, panels=None, battery=None, charging=None, controller=None):  # noqa: E501
        """DynamicDataGet200ResponseMessage - a model defined in OpenAPI

        :param load: The load of this DynamicDataGet200ResponseMessage.  # noqa: E501
        :type load: DynamicDataGet200ResponseMessageLoad
        :param faults: The faults of this DynamicDataGet200ResponseMessage.  # noqa: E501
        :type faults: List[str]
        :param modbus_error: The modbus_error of this DynamicDataGet200ResponseMessage.  # noqa: E501
        :type modbus_error: bool
        :param panels: The panels of this DynamicDataGet200ResponseMessage.  # noqa: E501
        :type panels: DynamicDataGet200ResponseMessagePanels
        :param battery: The battery of this DynamicDataGet200ResponseMessage.  # noqa: E501
        :type battery: DynamicDataGet200ResponseMessageBattery
        :param charging: The charging of this DynamicDataGet200ResponseMessage.  # noqa: E501
        :type charging: DynamicDataGet200ResponseMessageCharging
        :param controller: The controller of this DynamicDataGet200ResponseMessage.  # noqa: E501
        :type controller: DynamicDataGet200ResponseMessageController
        """
        self.openapi_types = {
            'load': DynamicDataGet200ResponseMessageLoad,
            'faults': List[str],
            'modbus_error': bool,
            'panels': DynamicDataGet200ResponseMessagePanels,
            'battery': DynamicDataGet200ResponseMessageBattery,
            'charging': DynamicDataGet200ResponseMessageCharging,
            'controller': DynamicDataGet200ResponseMessageController
        }

        self.attribute_map = {
            'load': 'load',
            'faults': 'faults',
            'modbus_error': 'modbusError',
            'panels': 'panels',
            'battery': 'battery',
            'charging': 'charging',
            'controller': 'controller'
        }

        self._load = load
        self._faults = faults
        self._modbus_error = modbus_error
        self._panels = panels
        self._battery = battery
        self._charging = charging
        self._controller = controller

    @classmethod
    def from_dict(cls, dikt) -> 'DynamicDataGet200ResponseMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _dynamic_data_get_200_response_message of this DynamicDataGet200ResponseMessage.  # noqa: E501
        :rtype: DynamicDataGet200ResponseMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def load(self) -> DynamicDataGet200ResponseMessageLoad:
        """Gets the load of this DynamicDataGet200ResponseMessage.


        :return: The load of this DynamicDataGet200ResponseMessage.
        :rtype: DynamicDataGet200ResponseMessageLoad
        """
        return self._load

    @load.setter
    def load(self, load: DynamicDataGet200ResponseMessageLoad):
        """Sets the load of this DynamicDataGet200ResponseMessage.


        :param load: The load of this DynamicDataGet200ResponseMessage.
        :type load: DynamicDataGet200ResponseMessageLoad
        """

        self._load = load

    @property
    def faults(self) -> List[str]:
        """Gets the faults of this DynamicDataGet200ResponseMessage.


        :return: The faults of this DynamicDataGet200ResponseMessage.
        :rtype: List[str]
        """
        return self._faults

    @faults.setter
    def faults(self, faults: List[str]):
        """Sets the faults of this DynamicDataGet200ResponseMessage.


        :param faults: The faults of this DynamicDataGet200ResponseMessage.
        :type faults: List[str]
        """

        self._faults = faults

    @property
    def modbus_error(self) -> bool:
        """Gets the modbus_error of this DynamicDataGet200ResponseMessage.


        :return: The modbus_error of this DynamicDataGet200ResponseMessage.
        :rtype: bool
        """
        return self._modbus_error

    @modbus_error.setter
    def modbus_error(self, modbus_error: bool):
        """Sets the modbus_error of this DynamicDataGet200ResponseMessage.


        :param modbus_error: The modbus_error of this DynamicDataGet200ResponseMessage.
        :type modbus_error: bool
        """

        self._modbus_error = modbus_error

    @property
    def panels(self) -> DynamicDataGet200ResponseMessagePanels:
        """Gets the panels of this DynamicDataGet200ResponseMessage.


        :return: The panels of this DynamicDataGet200ResponseMessage.
        :rtype: DynamicDataGet200ResponseMessagePanels
        """
        return self._panels

    @panels.setter
    def panels(self, panels: DynamicDataGet200ResponseMessagePanels):
        """Sets the panels of this DynamicDataGet200ResponseMessage.


        :param panels: The panels of this DynamicDataGet200ResponseMessage.
        :type panels: DynamicDataGet200ResponseMessagePanels
        """

        self._panels = panels

    @property
    def battery(self) -> DynamicDataGet200ResponseMessageBattery:
        """Gets the battery of this DynamicDataGet200ResponseMessage.


        :return: The battery of this DynamicDataGet200ResponseMessage.
        :rtype: DynamicDataGet200ResponseMessageBattery
        """
        return self._battery

    @battery.setter
    def battery(self, battery: DynamicDataGet200ResponseMessageBattery):
        """Sets the battery of this DynamicDataGet200ResponseMessage.


        :param battery: The battery of this DynamicDataGet200ResponseMessage.
        :type battery: DynamicDataGet200ResponseMessageBattery
        """

        self._battery = battery

    @property
    def charging(self) -> DynamicDataGet200ResponseMessageCharging:
        """Gets the charging of this DynamicDataGet200ResponseMessage.


        :return: The charging of this DynamicDataGet200ResponseMessage.
        :rtype: DynamicDataGet200ResponseMessageCharging
        """
        return self._charging

    @charging.setter
    def charging(self, charging: DynamicDataGet200ResponseMessageCharging):
        """Sets the charging of this DynamicDataGet200ResponseMessage.


        :param charging: The charging of this DynamicDataGet200ResponseMessage.
        :type charging: DynamicDataGet200ResponseMessageCharging
        """

        self._charging = charging

    @property
    def controller(self) -> DynamicDataGet200ResponseMessageController:
        """Gets the controller of this DynamicDataGet200ResponseMessage.


        :return: The controller of this DynamicDataGet200ResponseMessage.
        :rtype: DynamicDataGet200ResponseMessageController
        """
        return self._controller

    @controller.setter
    def controller(self, controller: DynamicDataGet200ResponseMessageController):
        """Sets the controller of this DynamicDataGet200ResponseMessage.


        :param controller: The controller of this DynamicDataGet200ResponseMessage.
        :type controller: DynamicDataGet200ResponseMessageController
        """

        self._controller = controller
