from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.name_get200_response_message import NameGet200ResponseMessage
from openapi_server import util

from openapi_server.models.name_get200_response_message import NameGet200ResponseMessage  # noqa: E501

class NameGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """NameGet200Response - a model defined in OpenAPI

        :param message: The message of this NameGet200Response.  # noqa: E501
        :type message: NameGet200ResponseMessage
        """
        self.openapi_types = {
            'message': NameGet200ResponseMessage
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'NameGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _name_get_200_response of this NameGet200Response.  # noqa: E501
        :rtype: NameGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> NameGet200ResponseMessage:
        """Gets the message of this NameGet200Response.


        :return: The message of this NameGet200Response.
        :rtype: NameGet200ResponseMessage
        """
        return self._message

    @message.setter
    def message(self, message: NameGet200ResponseMessage):
        """Sets the message of this NameGet200Response.


        :param message: The message of this NameGet200Response.
        :type message: NameGet200ResponseMessage
        """

        self._message = message
