from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.settings_get200_response_message import SettingsGet200ResponseMessage
from openapi_server import util

from openapi_server.models.settings_get200_response_message import SettingsGet200ResponseMessage  # noqa: E501

class SettingsGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, message=None):  # noqa: E501
        """SettingsGet200Response - a model defined in OpenAPI

        :param message: The message of this SettingsGet200Response.  # noqa: E501
        :type message: SettingsGet200ResponseMessage
        """
        self.openapi_types = {
            'message': SettingsGet200ResponseMessage
        }

        self.attribute_map = {
            'message': 'message'
        }

        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'SettingsGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _settings_get_200_response of this SettingsGet200Response.  # noqa: E501
        :rtype: SettingsGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> SettingsGet200ResponseMessage:
        """Gets the message of this SettingsGet200Response.


        :return: The message of this SettingsGet200Response.
        :rtype: SettingsGet200ResponseMessage
        """
        return self._message

    @message.setter
    def message(self, message: SettingsGet200ResponseMessage):
        """Sets the message of this SettingsGet200Response.


        :param message: The message of this SettingsGet200Response.
        :type message: SettingsGet200ResponseMessage
        """

        self._message = message
