from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SystemInfoGet200ResponseMessage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, max_support_voltage=None, reted_charging_current=None, rated_discharge_current=None, device_type=None, model=None, software_version=None, hardware_version=None, serial_number=None):  # noqa: E501
        """SystemInfoGet200ResponseMessage - a model defined in OpenAPI

        :param max_support_voltage: The max_support_voltage of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :type max_support_voltage: float
        :param reted_charging_current: The reted_charging_current of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :type reted_charging_current: float
        :param rated_discharge_current: The rated_discharge_current of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :type rated_discharge_current: float
        :param device_type: The device_type of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :type device_type: str
        :param model: The model of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :type model: str
        :param software_version: The software_version of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :type software_version: str
        :param hardware_version: The hardware_version of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :type hardware_version: str
        :param serial_number: The serial_number of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :type serial_number: str
        """
        self.openapi_types = {
            'max_support_voltage': float,
            'reted_charging_current': float,
            'rated_discharge_current': float,
            'device_type': str,
            'model': str,
            'software_version': str,
            'hardware_version': str,
            'serial_number': str
        }

        self.attribute_map = {
            'max_support_voltage': 'maxSupportVoltage',
            'reted_charging_current': 'retedChargingCurrent',
            'rated_discharge_current': 'ratedDischargeCurrent',
            'device_type': 'deviceType',
            'model': 'model',
            'software_version': 'softwareVersion',
            'hardware_version': 'hardwareVersion',
            'serial_number': 'serialNumber'
        }

        self._max_support_voltage = max_support_voltage
        self._reted_charging_current = reted_charging_current
        self._rated_discharge_current = rated_discharge_current
        self._device_type = device_type
        self._model = model
        self._software_version = software_version
        self._hardware_version = hardware_version
        self._serial_number = serial_number

    @classmethod
    def from_dict(cls, dikt) -> 'SystemInfoGet200ResponseMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _system_info_get_200_response_message of this SystemInfoGet200ResponseMessage.  # noqa: E501
        :rtype: SystemInfoGet200ResponseMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def max_support_voltage(self) -> float:
        """Gets the max_support_voltage of this SystemInfoGet200ResponseMessage.


        :return: The max_support_voltage of this SystemInfoGet200ResponseMessage.
        :rtype: float
        """
        return self._max_support_voltage

    @max_support_voltage.setter
    def max_support_voltage(self, max_support_voltage: float):
        """Sets the max_support_voltage of this SystemInfoGet200ResponseMessage.


        :param max_support_voltage: The max_support_voltage of this SystemInfoGet200ResponseMessage.
        :type max_support_voltage: float
        """

        self._max_support_voltage = max_support_voltage

    @property
    def reted_charging_current(self) -> float:
        """Gets the reted_charging_current of this SystemInfoGet200ResponseMessage.


        :return: The reted_charging_current of this SystemInfoGet200ResponseMessage.
        :rtype: float
        """
        return self._reted_charging_current

    @reted_charging_current.setter
    def reted_charging_current(self, reted_charging_current: float):
        """Sets the reted_charging_current of this SystemInfoGet200ResponseMessage.


        :param reted_charging_current: The reted_charging_current of this SystemInfoGet200ResponseMessage.
        :type reted_charging_current: float
        """

        self._reted_charging_current = reted_charging_current

    @property
    def rated_discharge_current(self) -> float:
        """Gets the rated_discharge_current of this SystemInfoGet200ResponseMessage.


        :return: The rated_discharge_current of this SystemInfoGet200ResponseMessage.
        :rtype: float
        """
        return self._rated_discharge_current

    @rated_discharge_current.setter
    def rated_discharge_current(self, rated_discharge_current: float):
        """Sets the rated_discharge_current of this SystemInfoGet200ResponseMessage.


        :param rated_discharge_current: The rated_discharge_current of this SystemInfoGet200ResponseMessage.
        :type rated_discharge_current: float
        """

        self._rated_discharge_current = rated_discharge_current

    @property
    def device_type(self) -> str:
        """Gets the device_type of this SystemInfoGet200ResponseMessage.


        :return: The device_type of this SystemInfoGet200ResponseMessage.
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type: str):
        """Sets the device_type of this SystemInfoGet200ResponseMessage.


        :param device_type: The device_type of this SystemInfoGet200ResponseMessage.
        :type device_type: str
        """

        self._device_type = device_type

    @property
    def model(self) -> str:
        """Gets the model of this SystemInfoGet200ResponseMessage.


        :return: The model of this SystemInfoGet200ResponseMessage.
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model: str):
        """Sets the model of this SystemInfoGet200ResponseMessage.


        :param model: The model of this SystemInfoGet200ResponseMessage.
        :type model: str
        """

        self._model = model

    @property
    def software_version(self) -> str:
        """Gets the software_version of this SystemInfoGet200ResponseMessage.


        :return: The software_version of this SystemInfoGet200ResponseMessage.
        :rtype: str
        """
        return self._software_version

    @software_version.setter
    def software_version(self, software_version: str):
        """Sets the software_version of this SystemInfoGet200ResponseMessage.


        :param software_version: The software_version of this SystemInfoGet200ResponseMessage.
        :type software_version: str
        """

        self._software_version = software_version

    @property
    def hardware_version(self) -> str:
        """Gets the hardware_version of this SystemInfoGet200ResponseMessage.


        :return: The hardware_version of this SystemInfoGet200ResponseMessage.
        :rtype: str
        """
        return self._hardware_version

    @hardware_version.setter
    def hardware_version(self, hardware_version: str):
        """Sets the hardware_version of this SystemInfoGet200ResponseMessage.


        :param hardware_version: The hardware_version of this SystemInfoGet200ResponseMessage.
        :type hardware_version: str
        """

        self._hardware_version = hardware_version

    @property
    def serial_number(self) -> str:
        """Gets the serial_number of this SystemInfoGet200ResponseMessage.


        :return: The serial_number of this SystemInfoGet200ResponseMessage.
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number: str):
        """Sets the serial_number of this SystemInfoGet200ResponseMessage.


        :param serial_number: The serial_number of this SystemInfoGet200ResponseMessage.
        :type serial_number: str
        """

        self._serial_number = serial_number
